{
 "title": "Opensearch Summary (VM)",
 "description": "ElasticSearch cluster stats.\r\n\r\nRevision 1 of this dashboard is the same as the Infinity Dashboard Revision 4 (https://grafana.com/dashboards/2322)\r\n\r\nThis is a cleaned up copy with all control characters removed from the dashboard file.  When downloading version 4 of the original Infinity elasticsearch dashboard via curl, the resulting file is corrupted with a missing final curly brace.\r\n",
 "tags": [
  "elasticsearch",
  "graylog",
  "vm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "description": "Shows status of cluster. Possible values: green, yellow, red",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{color=~\"red\", instance=\"$instance\"} == 1\r\nor (elasticsearch_cluster_health_status{color=\"green\", instance=\"$instance\"} == 1) + 4\r\nor (elasticsearch_cluster_health_status{color=\"yellow\", instance=\"$instance\"} == 1) + 22",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "stat",
   "description": "This indicates the number of times an Elasticsearch circuit breaker has been triggered.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}>0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "description": "The average CPU usage across Elasticsearch nodes in a cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "description": "The percentage of used JVM memory in Elasticsearch.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "stat",
   "description": "Shows open file descriptors in instance",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "stat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC count",
   "type": "timeseries",
   "description": "The rate of JVM garbage collection (GC) events per second over a short time window.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "description": "Time spent on JVM garbage collection (GC) per second over a short time window:",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total translog operations",
   "type": "timeseries",
   "description": "The rate of transaction log (translog) operations per second over a short time window",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "timeseries",
   "description": "Total translog size in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Tripped for breakers",
   "type": "timeseries",
   "description": "This metric shows whether any circuit breakers have been triggered to prevent memory overload in Elasticsearch.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_breakers_tripped{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "timeseries",
   "description": "This metric shows the estimated memory usage (in bytes) for circuit breakers in Elasticsearch.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_breakers_estimated_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    },
    {
     "expr": "elasticsearch_breakers_limit_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: limit for {{breaker}}"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "It represents the 1-minute load average of the operating system running Elasticsearch.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The CPU usage of the Elasticsearch process as a percentage of total CPU capacity.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "description": "This metric represents the amount of JVM heap memory currently in use by Elasticsearch.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "timeseries",
   "description": "This metric shows the amount of heap memory that the JVM has committed for use.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "This metric calculates the percentage of used disk space in Elasticsearch data storage.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "description": "This metric measures the rate of data transmitted (in bytes) over the transport layer in Elasticsearch.\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Documents count on node",
   "type": "timeseries",
   "description": "his metric represents the total number of documents stored in the Elasticsearch indices for a given instance and cluster.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "timeseries",
   "description": "This metric calculates the rate of documents being indexed per second over the specified interval.\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "timeseries",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "timeseries",
   "description": "This calculates the rate of documents merged per second over the specified interval.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "timeseries",
   "description": "This metric calculates the rate of merged segment size (in bytes) per second over the specified interval.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Query time",
   "type": "timeseries",
   "description": "Rate of time spent on search queries per second.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "description": "Rate of time spent indexing documents per second.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "description": "Rate of total time spent merging index segments per second.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "description": "Rate of time Elasticsearch spent throttling store operations per second.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Total Operations rate",
   "type": "timeseries",
   "description": "Rate of documents indexed per second in Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_tota{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "description": "Instantaneous rate of time spent indexing documents in Elasticsearch, measured in seconds.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "description": "Instantaneous rate of rejected thread pool tasks in Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "timeseries",
   "description": "Current number of active threads in the Elasticsearch thread pool.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 20, "w": 6, "x": 6, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "description": "Displays the number of active threads currently in use by the Elasticsearch thread pool.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 20, "w": 6, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "description": "Measures the rate of completed tasks in the Elasticsearch thread pool over the specified interval.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 20, "w": 6, "x": 18, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Field data memory size",
   "type": "timeseries",
   "description": "Represents the memory used by field data in Elasticsearch, measured in bytes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "timeseries",
   "description": "Represents the rate of field data evictions from memory in Elasticsearch over the specified interval.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "description": "Shows the amount of memory used by the Elasticsearch query cache in bytes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "timeseries",
   "description": "Rate of query cache evictions in Elasticsearch, indicating how often cached queries are being removed.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Evictions from filter cache",
   "type": "timeseries",
   "description": "Rate of filter cache evictions in Elasticsearch, showing how frequently filter cache entries are being removed.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_filter_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "Count of index segments",
   "type": "timeseries",
   "description": "Total number of segments in Elasticsearch indices, indicating index fragmentation and merge activity.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current memory size of segments in bytes",
   "type": "timeseries",
   "description": "Total memory used by Elasticsearch index segments, including stored fields, terms, and norms.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 }
  },
  {
   "title": "Count of documents with only primary shards",
   "type": "timeseries",
   "description": "Number of primary documents stored in the Elasticsearch index.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with only primary shards on all nodes",
   "type": "timeseries",
   "description": "Total size of stored index data in bytes with only primary shards on all nodes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with all shards on all nodes",
   "type": "timeseries",
   "description": "Total size of stored index data in bytes with all shards on all nodes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Index writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "Index writer with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Index writer with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Index writer with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Index writer with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 246 } },
  {
   "title": "Segments with only primary shards on all nodes",
   "type": "timeseries",
   "description": "Number of primary segments in the Elasticsearch index.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Segments with all shards on all nodes",
   "type": "timeseries",
   "description": "Total number of segments across all shards in the Elasticsearch index.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of segments with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of segments with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Doc values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Doc values with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Memory used by primary shard segments for doc values in Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Doc values with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Doc values with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fields", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 290 } },
  {
   "title": "Size of fields with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of fields with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 291 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fields with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of fields with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fixed bit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 305 } },
  {
   "title": "Size of fixed bit with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Memory used by primary shard segments for fixed bit sets in Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 306 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fixed bit with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Total memory used by shard segments for fixed bit sets in Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Norms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 320 } },
  {
   "title": "Size of norms with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of norms with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of norms with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of norms with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 328 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 335 } },
  {
   "title": "Size of points with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of points with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 336 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of points with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of points with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 343 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Terms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 350 } },
  {
   "title": "Size of terms with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of terms with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 351 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_terms_memory_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Number of terms with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Number of terms with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 358 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_terms_memory_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Version map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 365 } },
  {
   "title": "Size of version map with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of version map with only primary shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 366 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of version map with all shards on all nodes in bytes",
   "type": "timeseries",
   "description": "Size of version map with all shards on all nodes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 373 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}