{
 "title": "MongoDB Summary (VM)",
 "tags": [
  "MongoDB",
  "Percona",
  "vm",
  "graylog"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gl_input_throughput,cluster)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(gl_input_throughput,instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "About dashboard and metrics exporter\n\nFor collecting MongoDB metrics [MongoDB exporter](https://github.com/percona/mongodb_exporter) is used. \nDashboard was imported from [repository](https://github.com/percona/grafana-dashboards/tree/main/dashboards/MongoDB)."
   }
  },
  {
   "title": "Node",
   "type": "text",
   "description": "VM address",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": {
    "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-host=$host\" target=\"_blank\">$host</a></h5>"
   }
  },
  {
   "title": "MongoDB Uptime",
   "type": "stat",
   "description": "Shows the uptime of MongoDB instance on VM",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_instance_uptime_seconds{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Shows statistics of operations with types \"insert\", \"query\", \"update\", \"delete\", \"getmore\"",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[5m]) or rate(mongodb_op_counters_total{instance=~\"$host\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{instance=~\"$host\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Shows combined latency",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_op_latencies_latency_total{instance=~\"$host\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{instance=~\"$host\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{instance=~\"$host\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{instance=~\"$host\",type=\"command\"}[5m]) > 0))"
    }
   ]
  },
  {
   "title": "Current ReplSet State",
   "type": "stat",
   "description": "This shows the role of the selected service. Normally this should be one of ``PRIMARY``, ``SECONDARY`` and ``ARBITER``, but if the system is newly added it could show ``STARTUP2`` during its initial sync.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (mongodb_up{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": " States",
   "type": "state-timeline",
   "description": "Read more about [Replica Set Member States](https://docs.mongodb.com/manual/reference/replica-states/).",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (set) (mongodb_up{instance=~\"$host\"})",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type!~\"(command|query|getmore)\"}[5m]) or\nrate(mongodb_mongos_op_counters_repl_total{instance=~\"$host\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongos_op_counters_repl_total{instance=~\"$host\", type!~\"(command|query|getmore)\"}[5m]))",
     "legendFormat": "repl_{{type}}"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Latency Detail",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (instance,type) (rate(mongodb_mongod_op_latencies_latency_total{instance=~\"$host\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{instance=~\"$host\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{instance=~\"$host\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{instance=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "TCP connections (Incoming)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_mongod_connections{instance=~\"$host\", state=\"current\"} or\nmongodb_mongos_connections{instance=~\"$host\", state=\"current\"} or\nmongodb_connections{instance=~\"$host\", state=\"current\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "description": "Open cursors. Includes idle cursors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance,state) (mongodb_mongod_metrics_cursor_open{instance=~\"$host\"} or\nmongodb_mongod_cursors{instance=~\"$host\"} or\nmongodb_mongos_metrics_cursor_open{instance=~\"$host\"} or \nmongodb_mongos_cursors{instance=~\"$host\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Docs per second inserted, updated, deleted or returned. (N.b. not 1-to-1 with operation counts.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance,state) (rate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Operations queued due to a lock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance,type) (mongodb_mongod_global_lock_current_queue{instance=~\"$host\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "timeseries",
   "description": "Ratio of Documents returned or Index entries scanned / full documents scanned",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{instance=~\"$host\", state=\"returned\"}[$interval]))/\nsum(rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned_objects\"}[$interval])) \nor\nsum(irate(mongodb_mongod_metrics_document_total{instance=~\"$host\", state=\"returned\"}[5m]))/\nsum(irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned_objects\"}[5m]))",
     "legendFormat": "Document"
    },
    {
     "expr": "(sum(rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned\"}[$interval]))/\nsum(rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned_objects\"}[$interval])) \nor\nsum(irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned\"}[5m]))/\nsum(irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\", state=\"scanned_objects\"}[5m])))",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "timeseries",
   "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned)) as well as the number of documents that were moved to a new location due to the size of the document growing. Moved documents only apply to the MMAPv1 storage engine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "timeseries",
   "description": "Legacy driver operation: Number of, and Sum of time spent, per second executing getLastError commands to confirm write concern.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$host\"}[$__rate_interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$host\"}[$__rate_interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$host\"}[5m]))",
     "legendFormat": "Write Wait Time"
    }
   ]
  },
  {
   "title": "getLastError Write Operations",
   "type": "timeseries",
   "description": "Legacy driver operation: Number of getLastError commands that timed out trying to confirm write concern.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=~\"$host\"}[$interval]) or\nirate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=~\"$host\"}[$interval]) or\nirate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance,type) (rate(mongodb_mongod_asserts_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_asserts_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_asserts_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_asserts_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_mongos_extra_info_page_faults_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_mongos_extra_info_page_faults_total{instance=~\"$host\"}[5m]) or\nrate(mongodb_extra_info_page_faults_total{instance=~\"$host\"}[$interval]) or \nirate(mongodb_extra_info_page_faults_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}