---

quiet: true

skip-check:
  - CKV_ANSIBLE_1 # Ensure that certificate validation isn't disabled with uri
  - CKV_ANSIBLE_2 # Ensure that certificate validation isn't disabled with get_url
  - CKV2_ANSIBLE_3 # Ensure block is handling task errors properly
  - CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty.